version: '3.4'

services:
  horsemoney:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: >
      /bin/bash -c "
        while !</dev/tcp/db/5432; do sleep 1; done;
        dotnet ef database update
      "

  db:
    image: postgres
    environment:
      POSTGRES_DB: dbHorseMoney
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
